# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-18 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetailsModel',
            fields=[
                ('id', models.AutoField(db_column='ID', editable=False, primary_key=True, serialize=False)),
                ('createDate', models.DateTimeField(auto_now_add=True, db_column='CREATE_DATE')),
                ('updateDate', models.DateTimeField(auto_now=True, db_column='UPDATE_DATE')),
                ('name', models.CharField(db_column='NAME', max_length=36, null=True, verbose_name='联系人')),
                ('email', models.CharField(db_column='EMAIL', max_length=36, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(db_column='PHONE', max_length=36, null=True, verbose_name='手机号码')),
                ('balanceAmount', models.DecimalField(db_column='BALANCE_AMOUNT', decimal_places=2, default=0, max_digits=10, null=True, verbose_name='余额')),
                ('creatorId', models.CharField(db_column='CREATOR_ID', max_length=36, null=True, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'LaunchUserDetails',
            },
        ),
    ]
