# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-18 09:27
from __future__ import unicode_literals

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(db_column='ID', default=account.models._uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=0)),
                ('createDate', models.DateTimeField(auto_now_add=True, db_column='CREATE_DATE', null=True)),
                ('updateDate', models.DateTimeField(auto_now=True, db_column='UPDATE_DATE', null=True)),
                ('userId', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account',
                'ordering': ['-createDate'],
            },
        ),
        migrations.CreateModel(
            name='AccountSlip',
            fields=[
                ('id', models.CharField(db_column='ID', default=account.models._uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('changeAmount', models.DecimalField(blank=True, db_column='CHANGE_AMOUNT', decimal_places=2, max_digits=10, null=True)),
                ('balanceType', models.IntegerField(blank=True, db_column='BALANCE_TYPE', null=True)),
                ('balance', models.DecimalField(blank=True, db_column='BALANCE', decimal_places=2, max_digits=10, null=True)),
                ('status', models.IntegerField(blank=True, db_column='STATUS', null=True)),
                ('slipDay', models.DateTimeField(blank=True, db_column='SLIP_DAY', null=True)),
                ('creatorId', models.IntegerField(blank=True, db_column='CREATOR_ID', null=True)),
                ('rechargeId', models.CharField(blank=True, db_column='RECHARGE_ID', default=None, max_length=36, null=True)),
                ('createDate', models.DateTimeField(auto_now_add=True, db_column='CREATE_DATE', null=True)),
                ('updateDate', models.DateTimeField(auto_now=True, db_column='UPDATE_DATE', null=True)),
                ('accountId', models.ForeignKey(db_column='ACCOUNT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='account', to='account.Account')),
            ],
            options={
                'db_table': 'account_slip',
                'ordering': ['-slipDay'],
            },
        ),
    ]
