# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-24 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='userId',
        ),
        migrations.AddField(
            model_name='account',
            name='creatorId',
            field=models.IntegerField(blank=True, db_column='CREATOR_ID', null=True),
        ),
    ]
