# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-28 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(db_column='ID', editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='TITLE', max_length=255, null=True, verbose_name='帖子标题')),
                ('subhead', models.CharField(db_column='SUBHEAD', max_length=255, null=True, verbose_name='帖子副标题')),
                ('transRate', models.FloatField(db_column='TRANS_RATE', max_length=20, null=True, verbose_name='离线转化率')),
                ('topic', models.CharField(db_column='TOPIC', max_length=255, null=True, verbose_name='帖子话题')),
                ('recommend', models.DecimalField(db_column='RECOMMEND', decimal_places=1, max_digits=3, verbose_name='推荐数')),
                ('recuperate', models.IntegerField(db_column='RECUPERATE', verbose_name='回帖数')),
                ('lightRecuperate', models.IntegerField(db_column='LIGHT_RECUPERATE', verbose_name='亮回帖数')),
                ('createDate', models.DateTimeField(auto_now_add=True, db_column='CREATE_DATE', verbose_name='发帖时间')),
                ('plate', models.CharField(db_column='PLATE', max_length=255, null=True, verbose_name='版块')),
                ('status', models.IntegerField(db_column='STATUS', verbose_name='帖子使用状态')),
                ('deleted', models.IntegerField(db_column='DELETED', verbose_name='帖子删除状态')),
                ('is_usable', models.IntegerField(db_column='IS_USED', verbose_name='是否可用')),
                ('updateDate', models.DateTimeField(auto_now=True, db_column='UPDATE_DATE', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '帖吧',
                'verbose_name_plural': '帖吧',
                'db_table': 'Hupu',
                'ordering': ['-createDate'],
            },
        ),
    ]
