# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-19 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import house.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(db_column='ID', editable=False, primary_key=True, serialize=False)),
                ('createDate', models.DateTimeField(auto_now_add=True, db_column='CREATE_DATE')),
                ('updateDate', models.DateTimeField(auto_now=True, db_column='UPDATE_DATE')),
                ('status', models.IntegerField(db_column='STATUS', default=0, verbose_name='状态')),
                ('province', models.CharField(db_column='PROVINCE', max_length=10, verbose_name='省份')),
                ('city', models.CharField(db_column='CITY', max_length=20, verbose_name='城市')),
                ('area', models.CharField(db_column='AREA', max_length=50, verbose_name='区域')),
                ('address', models.CharField(db_column='ADDRESS', max_length=500, verbose_name='详细地址')),
                ('price', models.DecimalField(db_column='PRICE', decimal_places=2, max_digits=10, verbose_name='价格')),
                ('priceType', models.IntegerField(choices=[(1, '月付'), (2, '季付'), (3, '半年付'), (4, '年付')], db_column='PRICE_TYPE', null=True, verbose_name='支付方式')),
                ('pledge', models.DecimalField(db_column='PLEDGE', decimal_places=2, max_digits=10, verbose_name='押金')),
                ('creatorId', models.CharField(blank=True, db_column='CREATOR_ID', max_length=255, null=True, verbose_name='用户id')),
            ],
            options={
                'verbose_name': '房屋信息',
                'verbose_name_plural': '房屋信息',
                'db_table': 'House',
                'ordering': ['-createDate'],
            },
        ),
        migrations.CreateModel(
            name='HouseImg',
            fields=[
                ('id', models.AutoField(db_column='ID', editable=False, primary_key=True, serialize=False)),
                ('createDate', models.DateTimeField(auto_now_add=True, db_column='CREATE_DATE')),
                ('updateDate', models.DateTimeField(auto_now=True, db_column='UPDATE_DATE')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('imageUrl', models.FileField(blank=True, db_column='IMAGE_URL', null=True, upload_to=house.models.upload_img, verbose_name='图片地址')),
                ('creatorId', models.CharField(blank=True, db_column='CREATOR_ID', max_length=255, null=True, verbose_name='用户id')),
                ('houseId', models.ForeignKey(db_column='HOUSE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='house', to='house.House', verbose_name='房间ID')),
            ],
            options={
                'verbose_name': '房屋图片',
                'verbose_name_plural': '房屋图片',
                'db_table': 'HouseImg',
                'ordering': ['-createDate'],
            },
        ),
        migrations.CreateModel(
            name='RentInfo',
            fields=[
                ('id', models.AutoField(db_column='ID', editable=False, primary_key=True, serialize=False)),
                ('createDate', models.DateTimeField(auto_now_add=True, db_column='CREATE_DATE')),
                ('updateDate', models.DateTimeField(auto_now=True, db_column='UPDATE_DATE')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
